'use client';

import React, { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { StatusBadge, LoadingSpinner } from '@/components/ui';
import type { Invoice } from '@/lib/types';

export default function MyInvoicesPage() {
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.getMyInvoices().then((data) => {
      setInvoices(data);
      setLoading(false);
    }).catch(() => setLoading(false));
  }, []);

  if (loading) return <LoadingSpinner />;

  return (
    <div>
      <div className="page-header">
        <h1 className="page-title">My Invoices</h1>
        <p className="page-subtitle">View and manage your fee invoices</p>
      </div>

      {invoices.length === 0 ? (
        <div className="card p-8 text-center text-slate-500">
          No invoices found. Invoices will appear here once generated by the administration.
        </div>
      ) : (
        <div className="space-y-4">
          {invoices.map((inv) => (
            <div key={inv.id} className="card p-6">
              <div className="flex items-start justify-between mb-4">
                <div>
                  <h3 className="font-semibold text-slate-900">{inv.invoiceNumber}</h3>
                  <p className="text-sm text-slate-500">{inv.feeStructure?.name}</p>
                </div>
                <StatusBadge status={inv.status} />
              </div>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
                <div>
                  <span className="text-slate-500">Total Amount</span>
                  <p className="font-semibold text-slate-900">${inv.amount.toLocaleString()}</p>
                </div>
                <div>
                  <span className="text-slate-500">Paid Amount</span>
                  <p className="font-semibold text-success-600">${inv.paidAmount.toLocaleString()}</p>
                </div>
                <div>
                  <span className="text-slate-500">Balance</span>
                  <p className="font-semibold text-danger-600">${(inv.amount - inv.paidAmount).toLocaleString()}</p>
                </div>
                <div>
                  <span className="text-slate-500">Due Date</span>
                  <p className="font-medium">{new Date(inv.dueDate).toLocaleDateString()}</p>
                </div>
              </div>

              {/* Payments history */}
              {inv.payments && inv.payments.length > 0 && (
                <div className="mt-4 border-t border-slate-100 pt-3">
                  <p className="text-xs font-medium text-slate-500 mb-2">Payment History</p>
                  {inv.payments.map((p) => (
                    <div key={p.id} className="flex items-center justify-between text-xs py-1">
                      <span>${p.amount.toLocaleString()} via {p.method}</span>
                      <StatusBadge status={p.status} />
                    </div>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
